#!/bin/sh

python2 Layer_filter_boxblur.py
python2 Layer_filter_contour.py
python2 Layer_filter_edge_enhance_more.py
python2 Layer_filter_edge_enhance.py
python2 Layer_filter_emboss.py
python2 Layer_filter_find_edges.py
python2 Layer_function_add_modulo.py
python2 Layer_function_add.py
python2 Layer_function_autocontrast.py
python2 Layer_function_brightness.py
python2 Layer_function_color.py
python2 Layer_function_contrast.py
python2 Layer_function_difference.py
python2 Layer_function_flip.py
python2 Layer_function_hue.py
python2 Layer_function_mask.py
python2 Layer_function_multiply.py
python2 Layer_function_opacity.py
python2 Layer_function_overlay.py
python2 Layer_function_posterize.py
python2 Layer_function_screen.py
python2 Layer_function_select.py
python2 Layer_function_solarize.py
python2 Layer_function_subtract_modulo.py
python2 Layer_function_subtract.py